name:  Desplegar en DonDominio por FTP

on:
  push:
    branches:
      - main  # O la rama que usas

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: castmanu

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Eliminar extensiones .html en enlaces templates
        run: |
          find templates/ -type f -name "*.html" -exec sed -i 's/href="\([^"]*\)\.html"/href="\1"/g' {} +

      - name: Eliminar extensiones .html en enlaces js
        run: |
          find assets/js/ -type f -name "*.js" -exec sed -i 's/\.html//g' {} +

      - name: Reemplazar URL localhost por URL Fly
        run: |
          find assets/js/ -type f -exec sed -i 's|http://localhost:8000|https://castmanu.fly.dev|g' {} +

      - name: Rotar versi贸n JS y CSS (0-9) en HTML
        run: |
          echo "Rotando versiones JS y CSS..."

          find templates/ -name "*.html" | while IFS= read -r file; do
            echo "Procesando $file"

            # JS
            version_js=$(grep -oP 'src="[^"]+\.js\?v=\K[0-9]' "$file" | head -n 1)
            if [[ "$version_js" =~ ^[0-9]$ ]]; then
              next_version_js=$(( (version_js + 1) % 10 ))
              echo "JS versi贸n actual: $version_js, siguiente: $next_version_js"
              sed -i "s/\(src=\"[^\"]\+\.js\?v=\)$version_js/\1$next_version_js/g" "$file"
            else
              echo "Agregando versi贸n v=0 a JS"
              grep -q 'src="[^"]\+\.js?v=[0-9]"' "$file" || sed -i -E 's/(src="[^"]+\.js)"/\1?v=0"/g' "$file"
            fi

            # CSS
            version_css=$(grep -oP 'href="[^"]+\.css\?v=\K[0-9]' "$file" | head -n 1)
            if [[ "$version_css" =~ ^[0-9]$ ]]; then
              next_version_css=$(( (version_css + 1) % 10 ))
              echo "CSS versi贸n actual: $version_css, siguiente: $next_version_css"
              sed -i "s/\(href=\"[^\"]\+\.css\?v=\)$version_css/\1$next_version_css/g" "$file"
            else
              echo "Agregando versi贸n v=0 a CSS"
              grep -q 'href="[^"]\+\.css?v=[0-9]"' "$file" || sed -i -E 's/(href="[^"]+\.css)"/\1?v=0"/g' "$file"
            fi

          done

      - name: Subir archivos al servidor por FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./  # Carpeta local (desde el root del repo)
          server-dir: /public/  # Cambia esto si tu estructura es diferente
          exclude: |
            app/**
            .github/**
            .git/**
            DDNS/**
            env/**
            .gitignore
            database.sql
            iniciar.bat
            README.md
            swap_server.ps1